package com.screenplay.project.runners;

import io.cucumber.junit.CucumberOptions;
import net.serenitybdd.cucumber.CucumberWithSerenity;
import org.junit.runner.RunWith;

/**
 * JUnit runner that kicks off the Cucumber suite via Serenity BDD.
 *
 * <p>It scans all feature files under {@code src/test/resources/features}
 * and runs only the scenarios tagged with {@code @BuyDevicesHP_DDT}.
 * A JSON report is written to {@code build/cucumber-reports/json/cucumber.json}
 * and the full Serenity HTML report is generated by the {@code aggregate} Gradle task.</p>
 */
@RunWith(CucumberWithSerenity.class)
@CucumberOptions(
        features = "src/test/resources/features",
        glue = {"com.screenplay.project.stepdefinition"},
        plugin = {"json:build/cucumber-reports/json/cucumber.json", "summary"},
        snippets = CucumberOptions.SnippetType.CAMELCASE,
        tags = "@BuyDevicesHP_DDT"
)
public class RunnerOpenWebTest {
}
