#
#Thu Aug 10 03:44:07 ECT 2023
goog\:chromeOptions={args\=[remote-allow-origins\=*], extensions\=[]}
acceptInsecureCerts=false
goo\:chromeOptions={args\=[--remote-allow-origins--]}
browserName=chrome
